// Generated by scripts/generate-notes.mjs.
import Foundation

enum NotchReleaseNotes {
    static let all: [ReleaseNote] = [
        ReleaseNote(version: "0.0.0", headline: "Notch development preview", changes: [
            ReleaseNote.Change(title: "Independent Notch identity", detail: "Separate application settings, credentials and update channels."),
            ReleaseNote.Change(title: "Native Mac and Windows development", detail: "Feature parity and release qualification are still in progress. This preview is not a public release.")
        ])
    ]
}
