// Generated by scripts/generate-design.mjs. Edit shared/design-tokens.json.
import AppKit

enum NotchTokens {
    static let sideBodyDepth: CGFloat = 186 * 0.37606837606837606
    static let curlRadius: CGFloat = 103 * 0.37606837606837606
    static let bezelFillet: CGFloat = 28 * 0.37606837606837606
    static let cornerRadius: CGFloat = 78.8 * 0.37606837606837606
    static let padTop: CGFloat = 69.5 * 0.37606837606837606
    static let padBottom: CGFloat = 50.1 * 0.37606837606837606
    static let cellSpacing: CGFloat = 83.5 * 0.37606837606837606
    static let pillWidth: CGFloat = 26 * 0.37606837606837606
    static let pillHeight: CGFloat = 210 * 0.37606837606837606
    static let pillHotZone: CGFloat = 90 * 0.37606837606837606
    static let ringDiameter: CGFloat = 117 * 0.37606837606837606
    static let trackStroke: CGFloat = 15.5 * 0.37606837606837606
    static let progressStroke: CGFloat = 8 * 0.37606837606837606
    static let glyphSize: CGFloat = 46 * 0.37606837606837606
    static let ringLabelGap: CGFloat = 26.9 * 0.37606837606837606
    static let activityDiameter: CGFloat = 72 * 0.37606837606837606
    static let activityStroke: CGFloat = 5.5 * 0.37606837606837606
    static let orbDiameter: CGFloat = 124 * 0.37606837606837606
    static let orbStroke: CGFloat = 18 * 0.37606837606837606
    static let orbGap: CGFloat = 27 * 0.37606837606837606
    static let orbGlyph: CGFloat = 56 * 0.37606837606837606
    static let orbHotZone: CGFloat = 152 * 0.37606837606837606
    static let cardWidth: CGFloat = 600 * 0.37606837606837606
    static let cardCorner: CGFloat = 49.5 * 0.37606837606837606
    static let cardPadding: CGFloat = 32 * 0.37606837606837606
    static let tailLength: CGFloat = 75 * 0.37606837606837606
    static let tailHeight: CGFloat = 87 * 0.37606837606837606
    static let tailGap: CGFloat = 28 * 0.37606837606837606
    static let barHeight: CGFloat = 10.5 * 0.37606837606837606
    static let headerGap: CGFloat = 17 * 0.37606837606837606
    static let headerToBlock: CGFloat = 21 * 0.37606837606837606
    static let labelToBar: CGFloat = 16.8 * 0.37606837606837606
    static let barToUsed: CGFloat = 17.8 * 0.37606837606837606
    static let blockSpacing: CGFloat = 20 * 0.37606837606837606
    static let sessionRowGap: CGFloat = 10 * 0.37606837606837606
    static let statusDot: CGFloat = 17 * 0.37606837606837606
    static let statusDotStroke: CGFloat = 3.4 * 0.37606837606837606
    static let statusDotGap: CGFloat = 11 * 0.37606837606837606
    static let hairline: CGFloat = 2.5 * 0.37606837606837606
    static let codexUsageTop: CGFloat = 20 * 0.37606837606837606
    static let codexMetricTop: CGFloat = 14 * 0.37606837606837606
    static let codexMetricRowGap: CGFloat = 8 * 0.37606837606837606
    static let codexMetricRowHeight: CGFloat = 40 * 0.37606837606837606
    static let codexMetricBottom: CGFloat = 14 * 0.37606837606837606
    static let codexUsageRowGap: CGFloat = 12 * 0.37606837606837606
    static let codexChartTop: CGFloat = 15 * 0.37606837606837606
    static let codexChartHeight: CGFloat = 115 * 0.37606837606837606
    static let endSlack: CGFloat = 190 * 0.37606837606837606
}
