// Generated by scripts/generate-design.mjs. Edit shared/design-tokens.json.
import AppKit

enum NotchTokens {
    static let designScale: CGFloat = 0.37606837606837606
    static let sideBodyDepth: CGFloat = 186 * designScale
    static let curlRadius: CGFloat = 103 * designScale
    static let bezelFillet: CGFloat = 28 * designScale
    static let cornerRadius: CGFloat = 78.8 * designScale
    static let padTop: CGFloat = 69.5 * designScale
    static let padBottom: CGFloat = 50.1 * designScale
    static let cellSpacing: CGFloat = 83.5 * designScale
    static let pillWidth: CGFloat = 26 * designScale
    static let pillHeight: CGFloat = 210 * designScale
    static let pillHotZone: CGFloat = 90 * designScale
    static let ringDiameter: CGFloat = 117 * designScale
    static let trackStroke: CGFloat = 15.5 * designScale
    static let progressStroke: CGFloat = 8 * designScale
    static let glyphSize: CGFloat = 46 * designScale
    static let ringLabelGap: CGFloat = 26.9 * designScale
    static let activityDiameter: CGFloat = 72 * designScale
    static let activityStroke: CGFloat = 5.5 * designScale
    static let orbDiameter: CGFloat = 124 * designScale
    static let orbStroke: CGFloat = 18 * designScale
    static let orbGap: CGFloat = 27 * designScale
    static let orbGlyph: CGFloat = 56 * designScale
    static let orbHotZone: CGFloat = 152 * designScale
    static let cardWidth: CGFloat = 600 * designScale
    static let cardCorner: CGFloat = 49.5 * designScale
    static let cardPadding: CGFloat = 32 * designScale
    static let tailLength: CGFloat = 75 * designScale
    static let tailHeight: CGFloat = 87 * designScale
    static let tailGap: CGFloat = 28 * designScale
    static let barHeight: CGFloat = 10.5 * designScale
    static let headerGap: CGFloat = 17 * designScale
    static let headerToBlock: CGFloat = 21 * designScale
    static let labelToBar: CGFloat = 16.8 * designScale
    static let barToUsed: CGFloat = 17.8 * designScale
    static let blockSpacing: CGFloat = 20 * designScale
    static let sessionRowGap: CGFloat = 10 * designScale
    static let statusDot: CGFloat = 17 * designScale
    static let statusDotStroke: CGFloat = 3.4 * designScale
    static let statusDotGap: CGFloat = 11 * designScale
    static let hairline: CGFloat = 2.5 * designScale
    static let codexUsageTop: CGFloat = 20 * designScale
    static let codexMetricTop: CGFloat = 14 * designScale
    static let codexMetricRowGap: CGFloat = 8 * designScale
    static let codexMetricRowHeight: CGFloat = 40 * designScale
    static let codexMetricBottom: CGFloat = 14 * designScale
    static let codexUsageRowGap: CGFloat = 12 * designScale
    static let codexChartTop: CGFloat = 15 * designScale
    static let codexChartHeight: CGFloat = 115 * designScale
    static let endSlack: CGFloat = 190 * designScale
}

enum NotchColors {
    static let notch: UInt32 = 0x000000
    static let card: UInt32 = 0x000000
    static let ringTrack: UInt32 = 0x303030
    static let barTrack: UInt32 = 0x2D2D2D
    static let ample: UInt32 = 0x00FF88
    static let watch: UInt32 = 0xF2FF00
    static let critical: UInt32 = 0xFF3F00
    static let textPrimary: UInt32 = 0xFFFFFF
    static let textSecondary: UInt32 = 0x808080
}
