import fs from 'node:fs';

const tokens = JSON.parse(fs.readFileSync('shared/design-tokens.json', 'utf8'));
const kebab = name => name.replace(/[A-Z]/g, letter => `-${letter.toLowerCase()}`);
const dimensions = Object.entries(tokens.geometry);
const colors = Object.entries(tokens.colors);
const swift = '// Generated by scripts/generate-design.mjs. Edit shared/design-tokens.json.\nimport AppKit\n\nenum NotchTokens {\n'
  + `    static let designScale: CGFloat = ${tokens.scale}\n`
  + dimensions.map(([name, pixels]) => `    static let ${name}: CGFloat = ${pixels} * designScale`).join('\n')
  + '\n}\n\nenum NotchColors {\n'
  + colors.map(([name, hex]) => `    static let ${name}: UInt32 = 0x${hex.slice(1)}`).join('\n')
  + '\n}\n';
const css = '/* Generated by scripts/generate-design.mjs. */\n:root {\n'
  + dimensions.map(([name, pixels]) => `  --${kebab(name)}: ${pixels * tokens.scale}px;`).join('\n')
  + '\n' + colors.map(([name, hex]) => `  --${kebab(name)}: ${hex};`).join('\n') + '\n}\n';
const outputs = {
  'apps/macos/Sources/DesignSystem/NotchTokens.swift': swift,
  'apps/windows/notch/ui/tokens.css': css,
};
for (const [path, generated] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(path, 'utf8') !== generated) throw new Error(`${path} is stale; run node scripts/generate-design.mjs`);
  } else fs.writeFileSync(path, generated);
}
