import fs from 'node:fs';
const notes = JSON.parse(fs.readFileSync('shared/release-notes.json','utf8'));
const swiftString = text => JSON.stringify(text).replaceAll('\\/', '/');
const swift = '// Generated by scripts/generate-notes.mjs.\nimport Foundation\n\nenum NotchReleaseNotes {\n    static let all: [ReleaseNote] = [\n'
  + notes.map(note => `        ReleaseNote(version: ${swiftString(note.version)}, headline: ${swiftString(note.headline)}, changes: [\n`
    + note.changes.map(change => `            ReleaseNote.Change(title: ${swiftString(change.title)}, detail: ${swiftString(change.detail)})`).join(',\n')
    + '\n        ])').join(',\n') + '\n    ]\n}\n';
fs.writeFileSync('apps/macos/Sources/Settings/NotchReleaseNotes.swift', swift);
fs.writeFileSync('apps/windows/notch/ui/release-notes.json', JSON.stringify(notes,null,2)+'\n');
